# @Author: ajisetyoko <simslab-cs>
# @Date:   2020-01-13T13:35:47+08:00
# @Email:  aji.setyoko.second@gmail.com
# @Last modified by:   simslab-cs
# @Last modified time: 2020-03-23T16:29:45+08:00

work_dir: ./work_dir/recognition/set1_fold4_v0
# feeder
feeder: feeder.feeder_kinetics.Feeder_kinetics
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 180
  data_path: ./data/perset_npy/set1/4/train_data.npy
  label_path: ./data/perset_npy/set1/4/train_label.pkl
test_feeder_args:
  data_path: ./data/perset_npy/set1/4/val_data.npy
  label_path: ./data/perset_npy/set1/4/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 6
  dropout: 0.1
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.01
step: [100]

# training
eval_interval: 1
save_interval: 1
device: [0]
batch_size: 20
test_batch_size: 20
num_epoch: 150
