work_dir: ./work_dir/recognition/sl2_resample_1
# feeder
feeder: feeder.feeder_kinetics.Feeder_kinetics
train_feeder_args:
  random_choose: False
  random_move: False
  window_size: 50
  data_path: ./data/train_data.npy
  label_path: ./data/train_label.pkl
test_feeder_args:
  data_path: ./data/val_data.npy
  label_path: ./data/val_label.pkl

# model
model: net.st_gcn_original.Model
model_args:
  in_channels: 3
  num_class: 93
  dropout: 0.1
  edge_importance_weighting: True
  graph_args:
    layout: 'sign_lang'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.2
step: [100,400]

# training
eval_interval: 10
save_interval: 10
device: [0]
batch_size: 10
test_batch_size: 10
num_epoch: 1000
